# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20151209_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 9, 21, 10, 38, 60782)),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
