# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 03:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20151209_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 9, 21, 19, 30, 391931)),
        ),
    ]
