# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 05:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20151209_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='oss_url',
            field=models.FileField(help_text=b'Your Geometry file', upload_to=b'/Users/raajsupramanian/market/market/../geometry_files', verbose_name=b'Geometry File'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(help_text=b'Value in $'),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 9, 23, 33, 7, 463048)),
        ),
    ]
