# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20151209_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='oss_object',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 10, 0, 51, 22, 552236)),
        ),
    ]
