# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20151210_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 10, 2, 54, 14, 54655)),
        ),
    ]
