# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20151210_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 10, 4, 31, 48, 453412)),
        ),
    ]
