# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20151210_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bucket_id',
            field=models.CharField(default=b'a5673199-7a19-483a-b261-2fed2bebdf06', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 10, 6, 15, 10, 856328)),
        ),
    ]
